apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fcd-servicios-h2h-service
  title: FCD Servicios H2h Service
  description: |
    Servicios del proyecto H2H
  annotations:
    backstage.io/techdocs-ref: dir:./
    github.com/project-slug: ibkpe-org/fcd-servicios-h2h-service
  tags:
    - language:csharp
spec:
  type: service
  lifecycle: experimental
  owner: group:default/lending
  system: fcd
