name: '$(Rev:rr)' #  ( Not change it)

pr: none
####################
# Trigger after any commit to master or feature/** branch
# tags: NO SUPPORTED BY BITBUCKET CLOUD 
####################
trigger:
  batch: false
  branches:
    include:
    - refs/heads/master
    - refs/heads/main
  paths:
    include:
    - '*'
    exclude:
    - 'readme*'
    - 'README*'
    - 'Readme*'
    - 'docs/*'


####################
# Resources Repository
# ibkteam/dso-template
# branch: master ( Not change it)
####################
resources:  
  repositories:
    - repository: ibkTeamAzTemplates
      type: github
      endpoint: 'github-generic-user'
      name: ibkpe-org/ibkteam-azure-templates
      ref: master
      
  pipelines:
    - pipeline: pipelineorigindev   # Name of the pipeline resource #  ( Not change it)
      source: bcr-net-backend_cd-uat # Name of the triggering pipeline
      trigger:
        branches:
          include:
            - refs/heads/master
            - refs/heads/main
            - refs/heads/hotfix/*

####################
# Call the template of your preference
# check the template out :
# https://bitbucket.org/ibkteam/ibkteam-azure-templates
####################
extends:
  template: src/templates/dotnet-iis/cd-prod.yml@ibkTeamAzTemplates
  parameters:
    projectName: "DSO"                          # nombre de proyecto
    ibkTeamAzureTemplates: "ibkTeamAzTemplates"
    componentName: 'mdc-reportes-bcr'           # nombre de componente 
    website: true                               # tipo website legacy
    azDevopsPrivateAgentEnable: true            # se habilitará el agente privado
    azDevopsPoolName: 'local-productos-uat'     # nombre de pool desde donde se hará el despliegue
    sharedFolderPath: \\s503v217\sda\bse\app    # ruta de la carpeta compartida | Separado por coma si es más de un servidor: Ejm: \\server1\path,\\server2\path  
    deploymentCredentials: 'bcr-net-backend'    # nombre de grupo de variables asociado a las credenciales de despliegue IIS