namespace Interbank.Productos.Comercial.Fcd.Domain.Entities.DataTable.DB2
{
    public static class PagoMasiMae
    {
        public static IReadOnlyList<ColumnMapping> ObtenerColumnasDb2PagoMasiMae()
        {
            return new List<ColumnMapping>
            {
            new ColumnMapping("CO_COD_RET", 0, 2, s => s),
            new ColumnMapping("CO_COD_TRAN", 2, 4, s => s),
            new ColumnMapping("CO_COD_PROG", 6, 8, s => s),
            new ColumnMapping("CO_COD_USUA", 14, 8, s => s),
            new ColumnMapping("NU_OPERA", 22, 10, s => s),
            new ColumnMapping("NU_SEC_OPER", 32, 7, s => s),
            new ColumnMapping("FE_PROC", 39, 8, s => s),
            new ColumnMapping("NU_PLANILLA", 47, 10, s => s),
            new ColumnMapping("NU_SEC_PLA", 57, 7, s => s),
            new ColumnMapping("CO_COD_UNIC", 64, 10, s => s),
            new ColumnMapping("CO_REG_EMP", 74, 8, s => s),
            new ColumnMapping("CO_TDA_ORIG", 82, 3, s => s),
            new ColumnMapping("CO_TIP_CTA_CR", 85, 2, s => s),
            new ColumnMapping("CO_CTRL1_CR", 87, 2, s => s),
            new ColumnMapping("CO_CTRL2_CR", 89, 3, s => s),
            new ColumnMapping("CO_CTRL3_CR", 92, 3, s => s),
            new ColumnMapping("CO_CTRL4_CR", 95, 4, s => s),
            new ColumnMapping("NU_ACCT_CR", 99, 10, s => s),
            new ColumnMapping("CO_TIP_CTA_DB", 109, 2, s => s),
            new ColumnMapping("CO_CTRL1_DB", 111, 2, s => s),
            new ColumnMapping("CO_CTRL2_DB", 113, 3, s => s),
            new ColumnMapping("CO_CTRL3_DB", 116, 3, s => s),
            new ColumnMapping("CO_CTRL4_DB", 119, 4, s => s),
            new ColumnMapping("NU_ACCT_DB", 123, 10, s => s),
            new ColumnMapping("CO_EXTOR", 133, 1, s => s),
            new ColumnMapping("DE_SHORT_DESC", 134, 15, s => s),
            new ColumnMapping("IM_MONT_CR", 149, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("IM_MONT_DB", 164, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("CO_COBR_FORZ", 179, 1, s => s),
            new ColumnMapping("CO_COBR_PARC", 180, 1, s => s),
            new ColumnMapping("CO_FLAG_OCC", 181, 1, s => s),
            new ColumnMapping("CO_CTA_MON_CF", 182, 3, s => s),
            new ColumnMapping("CO_CTA_CLA_TC", 185, 2, s => s),
            new ColumnMapping("IM_CTA_TC_CF", 187, 15, s => decimal.Parse(s) / 1000000),
            new ColumnMapping("IM_CTA_IMP_EQUIV", 202, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("NU_LOG_EXT", 217, 7, s => decimal.Parse(s)),
            new ColumnMapping("CO_FLAG_PROC", 224, 1, s => s),
            new ColumnMapping("DE_DESC_DESEM", 225, 12, s => s),
            new ColumnMapping("CO_CCI_CTL1", 237, 2, s => s),
            new ColumnMapping("CO_CCI_CTL2", 239, 3, s => s),
            new ColumnMapping("CO_CCI_CTL3", 242, 3, s => s),
            new ColumnMapping("CO_CCI_CTL4", 245, 4, s => s),
            new ColumnMapping("CO_CCI_CTA_ORDE", 249, 10, s => s),
            new ColumnMapping("CO_COD_UNI_ORDE", 259, 10, s => s),
            new ColumnMapping("DE_NOMB_ORDE", 269, 40, s => s),
            new ColumnMapping("CO_COD_UNI_BENE", 309, 10, s => s),
            new ColumnMapping("CO_CCI_MONE", 319, 3, s => s),
            new ColumnMapping("IM_IMP_CCI", 322, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("NU_CTA_CCI", 337, 20, s => s),
            new ColumnMapping("DE_NOMB_BENE", 357, 40, s => s),
            new ColumnMapping("CO_FLAG_NETEA", 397, 1, s => s),
            new ColumnMapping("CO_BCR_TIP_DOC_A", 398, 2, s => s),
            new ColumnMapping("CO_BCR_NRO_DOC_A", 400, 11, s => s),
            new ColumnMapping("CO_BCR_TIP_DOC_G", 411, 2, s => s),
            new ColumnMapping("CO_BCR_NRO_DOC_G", 413, 11, s => s),
            new ColumnMapping("CO_STAT_PAGO", 424, 2, s => s),
            new ColumnMapping("CO_STAT_RETO", 426, 4, s => s),
            new ColumnMapping("DE_DES_MSG_ERR", 430, 70, s => s),
            new ColumnMapping("NU_NRO_DOCUM", 500, 10, s => s),
            new ColumnMapping("IM_IMP_DESEM", 510, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("CO_FLAG_EXT_RE", 525, 1, s => s),
            new ColumnMapping("NU_LOG_EXT_RE", 526, 7, s => decimal.Parse(s) / 100),
            new ColumnMapping("IM_IMP_COM_CCI", 533, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("IM_IMP_COM_IB", 548, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("IM_IMP_DES_CCI", 563, 15, s => decimal.Parse(s) / 100),
            new ColumnMapping("HO_PROC_FIN", 578, 8, s => s),
            new ColumnMapping("NU_INSTRUC", 586, 18, s => s),
            new ColumnMapping("CO_CLIENTE", 604, 10, s => s),
            new ColumnMapping("CO_TIPO_PROCESO", 614, 1, s => s),
            new ColumnMapping("CO_ENVIO_CORREO", 615, 1, s => s)
        };
        }
    }
}
